version: "3.9"

services:
  v2fly-simple-shadosocks-gateway:
    hostname: v2ray
    image: v2fly/v2fly-core
    network_mode: host
    ports:
      - 19822
    volumes:
      - ./build-configs/v2fly-shadowsocks.json:/etc/v2ray/config.json
    command: "run -c /etc/v2ray/config.json"

  v2fly-shadowsocks-websocket-tls-gateway:
    hostname: v2ray
    image: v2fly/v2fly-core
    network_mode: bridge
    ports:
      - "1333:1333"
      - "11333:11333"
      - "21333:21333"
    volumes:
      - ./build-configs/v2fly-shadowsocks-websocket-tls.json:/etc/v2ray/config.json
    command: "run -c /etc/v2ray/config.json"

  v2fly-shadowsocks-grpc-tls-gateway:
    hostname: v2ray
    image: v2fly/v2fly-core
    network_mode: bridge
    ports:
      - "10000:10000"
    volumes:
      - ./build-configs/v2fly-shadowsocks-grpc-tls.json:/etc/v2ray/config.json
    command: "run -c /etc/v2ray/config.json"

  v2fly-trojan-gateway:
    hostname: v2ray
    image: v2fly/v2fly-core
    network_mode: host
    ports:
      - 8433
    volumes:
      - ./build-configs/v2fly-trojan.json:/etc/v2ray/config.json
    command: "run -c /etc/v2ray/config.json"

  tor-gateway:
    hostname: tor
    build: 
      context: .
      dockerfile: Dockerfile.tor
    network_mode: bridge
    ports:
      - "9050:9050"
    restart: always


