version: "3.9"

services:
  v2fly-simple-shadosocks-gateway:
    hostname: v2ray
    image: v2fly/v2fly-core
    network_mode: host
    ports:
      - 19822
    volumes:
      - ./build-configs/v2fly-shadowsocks-in.json:/etc/v2ray/config.json
    command: "run -c /etc/v2ray/config.json"

  v2fly-shadowsocks-websocket-tls-gateway:
    hostname: v2ray
    image: v2fly/v2fly-core
    network_mode: bridge
    networks:
      v2fly:
        ipv4_address: 172.20.0.5
    ports:
      - "1333:1333"
      - "11333:11333"
      - "21333:21333"
    volumes:
      - ./build-configs/v2fly-shadowsocks-websocket-tls-in.json:/etc/v2ray/config.json
    command: "run -c /etc/v2ray/config.json"

  v2fly-shadowsocks-grpc-tls-gateway:
    hostname: v2ray
    image: v2fly/v2fly-core
    network_mode: bridge
    networks:
      v2fly:
        ipv4_address: 172.20.0.6
    ports:
      - "10000:10000"
    volumes:
      - ./build-configs/v2fly-shadowsocks-grpc-tls-in.json:/etc/v2ray/config.json
    command: "run -c /etc/v2ray/config.json"

  v2fly-trojan-gateway:
    hostname: v2ray
    image: v2fly/v2fly-core
    network_mode: bridge
    networks:
      v2fly:
        ipv4_address: 172.20.0.8
    ports:
      - "8443:8443"
    volumes:
      - ./build-configs/v2fly-trojan-in.json:/etc/v2ray/config.json
      - ./trojan-certs:/etc/v2ray/trojan-certs
    command: "run -c /etc/v2ray/config.json"

  v2fly-out-gateway:
    hostname: v2ray
    image: v2fly/v2fly-core
    network_mode: bridge
    networks:
      v2fly:
        ipv4_address: 172.20.0.7
    ports:
      - "1234:1234"
    volumes:
      - ./build-configs/v2fly-socks-out.json:/etc/v2ray/config.json
    command: "run -c /etc/v2ray/config.json"



