version: "3.9"

services:
  shadowsocks-simple-gateway:
    hostname: shadowsocks
    image: shadowsocks/shadowsocks-libev
    network_mode: host
    ports:
      - 10826
    volumes:
      - ./build-configs/shadowsocks-simple-gateway.json:/config.json
    restart: always
    command: ss-server -c /config.json

  shadowsocks-v2ray-plugin-gateway:
    hostname: shadowsocks
    image: shadowsocks/shadowsocks-libev
    network_mode: host
    ports:
      - 14877
    volumes:
      - ./build-configs/shadowsocks-v2ray-plugin-gateway.json:/config.json
    restart: always
    command: ss-server -c /config.json

  v2fly-simple-shadosocks-gateway:
    hostname: v2ray
    image: v2fly/v2fly-core
    network_mode: host
    ports:
      - 27544
    volumes:
      - ./build-configs/v2fly-shadowsocks.json:/etc/v2ray/config.json

  v2fly-shadowsocks-websocket-tls-gateway:
    hostname: v2ray
    image: v2fly/v2fly-core
    network_mode: bridge
    ports:
      - "10000:10000"
    volumes:
      - ./build-configs/v2fly-shadowsocks-websocket-tls.json:/etc/v2ray/config.json

  v2fly-shadowsocks-grpc-tls-gateway:
    hostname: v2ray
    image: v2fly/v2fly-core
    network_mode: bridge
    ports:
      - "42777:42777"
    volumes:
      - ./build-configs/v2fly-shadowsocks-grpc-tls.json:/etc/v2ray/config.json


